# Generated by Django 5.1.7 on 2025-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_user_todo_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="title",
            field=models.TextField(default="Title", max_length=30),
        ),
        migrations.AlterField(
            model_name="todo",
            name="description",
            field=models.TextField(max_length=300),
        ),
    ]
